NAMES = [
    "Aldric", "Varek", "Thalion", "Edrin", "Calmor", "Sereth", "Kaelen", "Rothar",
    "Beren", "Halvek", "Ithros", "Malric", "Darian", "Osmund", "Vaelor", "Torrin",
    "Erynd", "Kassor", "Ulric", "Nereth", "Balric", "Corvin", "Jareth", "Loric",
    "Mavren", "Talen", "Yorik", "Fenric", "Arveth", "Sorn", "Kelmar", "Ravian",
    "Theron", "Iskald", "Branor", "Zareth", "Odrin", "Valcor", "Drekon", "Aemon",
    "Rhogar", "Elric", "Korrin", "Stavros", "Myren", "Vastin", "Althor", "Nykor",
    "Graven", "Eldric", "Torveth", "Cassian", "Morvek", "Ilyas", "Kethryn",
    "Valen", "Orimar", "Rendar", "Halcion", "Sevrin", "Kaedor", "Luthen",
    "Bastion", "Zorren", "Avarin", "Dravik", "Cyran", "Molrik", "Ethryn",
    "Varros", "Selyth", "Othran", "Tavrek", "Norik", "Phaedon", "Karn",
    "Ishmar", "Tharion", "Velkor", "Ashryn", "Torrek", "Erevain", "Zalyk",
    "Elowen", "Saelis", "Irielle", "Vaelis", "Nymera", "Aestra", "Luneth",
    "Seraphel", "Caelith", "Ysolde", "Myrren", "Thaelis", "Elyra", "Rhaelin",
    "Selune", "Ishara", "Velune", "Aelwyn", "Nymira", "Liraeth", "Solenne",
    "Kaelira", "Avenya", "Thessia", "Ilyeth", "Faelora", "Rynelle", "Erisyn",
    "Maelis", "Sylpha", "Arielle", "Vaereth", "Nyssara", "Elaris", "Celyne",
    "Aurelion", "Valerius", "Thamior", "Cassivar", "Eldamar",
    "Archael", "Magnor", "Septimus", "Caladorn", "Virex",
    "Domarion", "Helior", "Primarch", "Solivar", "Theomir",
    "Imperion", "Chronos", "Mythras", "Aethern", "Luxar"
]

ROLE_3_TITLES = [ "King", "Queen", "Emperor", "Prince", "Princess" ]
ROLE_2_TITLES = [ "Duke", "Duchess", "Count", "Countess", "General", "Commander" ]
ROLE_1_TITLES = [ "Baron", "Baroness", "Knight", "Lady", "Lord", "Captain", "Merchant" ]
ROLE_0_TITLES = [ "Peasant", "Farmer", "Soldier", "Artisan", "Trader", "Servant" ]

FACTION_NAMES = [
    "The Ashen Dominion",
    "The Silver Marches",
    "The Iron Concord",
    "The Black Banner",
    "The Sapphire Crown",
    "The Red River Compact",
    "The Gilded Throne",
    "The Obsidian Pact",
    "The Stormbound Realms",
    "The High Kingdom of Valmere",
    "The Broken Coast Confederacy",
    "The Ember Union",
    "The Dawnward Principality",
    "The Crown of Thorns",
    "The Verdant Accord",
    "The Frostbound Clans",
    "The Sunfall Empire",
    "The Nightspire League",
    "The Copper Reach",
    "The Kingdom of Hollow Peaks",
    "The Sea-Kings of Thalassar",
    "The Bannered Cities",
    "The Wolfstandard Realm",
    "The Golden Steppe",
    "The Pale March",
    "The Trine Alliance",
    "The Kingdom Beneath the Hills",
    "The Sovereignty of Glass",
    "The River-Crown States",
    "The Blackstone Regency",
]


RELIGION_NAMES = [
    "The Radiant Path",
    "The Old Faith",
    "The Veiled Doctrine",
    "The Ash Covenant",
    "The Silent Truth",
    "The Way of the Turning Wheel",
    "The Faith of Seven Fires",
    "The Deep Word",
    "The Starbound Creed",
    "The Children of the First Dawn",
    "The Final Testament",
    "The Church of the Unbroken Light",
    "The Black Litany",
    "The Thousandfold Way",
    "The Whispering Faith",
    "The Living Scripture",
    "The Cult of Returning Ash",
    "The Pilgrimage of Silence",
    "The Way of Sacred Blood",
    "The Last Revelation",
    "The Sky-Sealed Faith",
    "The Rootbound Belief",
    "The Faith of Waking Stone",
]


GOD_NAMES = [
    "Aurelion",
    "Thyrix",
    "Kael-Mor",
    "Veshra",
    "Ilyon",
    "Morveth",
    "Sathiel",
    "Neruun",
    "Vaelora",
    "Xath",
    "Eryndor",
    "Solkar",
    "Beloth",
    "Yssara",
    "Kharum",
    "Ulthain",
    "Myrr",
    "Zaleth",
    "Ophira",
    "Rethos",
    "Ankar",
    "Thalos",
    "Sereth",
]


CULTURE_NAMES = [
    "Valmeri",
    "Thalassi",
    "Korvani",
    "Eldric",
    "Ashkari",
    "Draekari",
    "Sylvanari",
    "Ironclad",
    "Holdari",
    "Wolframi",
    "Sunari",
    "Moonfolk",
    "Lokkron",
    "Hellonic",
    "Jorlokkian",
    "Gerudo",
    "Vashari",
    "Tarkani",
    "Nymari",
    "Zelphari",
    "Falkari",
    "Bronzehill Folk",
    "Stormreachers",
    "Sunward Nomads",
    "Hollowborn",
    "Frostvein Clans",
    "Redwater Tribes",
    "Highvale Kin",
    "Ironroot Dwarrow",
    "Coastbound",
    "Glassfolk",
    "Sandborn",
    "Nightlanders",
    "Deepwood Circles",
    "Riverwardens",
    "Skyfolk",
    "Blackreachers",
    "Stonewake",
    "Amber Coast Peoples",
]

WORLD_NAMES = [
    "Eldoria",
    "Valoria",
    "Terra",
    "Earth",
    "Aetheris",
    "Noveria",
]
